# Generated by Django 5.2.10 on 2026-01-26 21:53

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrewMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("rank", models.CharField(max_length=40)),
                ("clearance_level", models.IntegerField()),
                ("on_duty", models.BooleanField(default=True)),
                ("medical_hold", models.BooleanField(default=False)),
                ("last_medical_check", models.DateField(blank=True, null=True)),
                ("fatigue_index", models.FloatField(default=0.2)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalCrewMember",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("rank", models.CharField(max_length=40)),
                ("clearance_level", models.IntegerField()),
                ("on_duty", models.BooleanField(default=True)),
                ("medical_hold", models.BooleanField(default=False)),
                ("last_medical_check", models.DateField(blank=True, null=True)),
                ("fatigue_index", models.FloatField(default=0.2)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical crew member",
                "verbose_name_plural": "historical crew members",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalJobRoleCatalog",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(db_index=True, max_length=80)),
                ("code", models.CharField(db_index=True, max_length=10)),
                ("clearance_level", models.IntegerField()),
                ("department", models.CharField(max_length=60)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical job role catalog",
                "verbose_name_plural": "historical job role catalogs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="JobRoleCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("clearance_level", models.IntegerField()),
                ("department", models.CharField(max_length=60)),
            ],
        ),
    ]
