# Generated by Django 5.2.10 on 2026-01-27 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crew", "0002_initial"),
        ("maintenance", "0002_historicalship_ship_historicalmodule_ship_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crewmember",
            name="ship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="maintenance.ship",
            ),
        ),
        migrations.AddField(
            model_name="historicalcrewmember",
            name="ship",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="maintenance.ship",
            ),
        ),
    ]
