# Generated by Django 5.2.10 on 2026-02-02 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crew", "0004_require_ship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewmember",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crew.jobrolecatalog"
            ),
        ),
    ]
