#!/usr/bin/env bash
set -euo pipefail

GRAPHQL_LIMIT_ENABLED=${GRAPHQL_LIMIT_ENABLED:-0}
HEAVY_RATE=${HEAVY_RATE:-1.0}
HEAVY_PAGE_SIZE=${HEAVY_PAGE_SIZE:-3}
READ_WEIGHT=${READ_WEIGHT:-80}
WRITE_WEIGHT=${WRITE_WEIGHT:-20}
DURATION=${K6_DURATION:-${DURATION:-2m}}

echo "run_heavy_calc: HEAVY_CALC=true HEAVY_RATE=${HEAVY_RATE} HEAVY_PAGE_SIZE=${HEAVY_PAGE_SIZE} READ_WEIGHT=${READ_WEIGHT} WRITE_WEIGHT=${WRITE_WEIGHT} DURATION=${DURATION}"

GRAPHQL_LIMIT_ENABLED="${GRAPHQL_LIMIT_ENABLED}" \
docker compose --profile load run --rm --no-deps \
  -e RUN_SUBSCRIPTIONS=false \
  -e HEAVY_CALC=true \
  -e HEAVY_RATE="${HEAVY_RATE}" \
  -e HEAVY_PAGE_SIZE="${HEAVY_PAGE_SIZE}" \
  -e READ_WEIGHT="${READ_WEIGHT}" \
  -e WRITE_WEIGHT="${WRITE_WEIGHT}" \
  -e DURATION="${DURATION}" \
  k6
