# Generated by Django 5.2.10 on 2026-01-26 21:53

import django.db.models.deletion
import general_manager.measurement.measurement_field
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maintenance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HazardClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("storage_limit_per_module", models.IntegerField()),
                ("requires_eva", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="VendorCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=120)),
                ("vendor_code", models.CharField(max_length=12, unique=True)),
                ("sector", models.CharField(max_length=120)),
                ("rating", models.IntegerField()),
                ("preferred", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalHazardClass",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.CharField(db_index=True, max_length=10)),
                ("name", models.CharField(max_length=80)),
                ("storage_limit_per_module", models.IntegerField()),
                ("requires_eva", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical hazard class",
                "verbose_name_plural": "historical hazard classes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVendorCatalog",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=120)),
                ("vendor_code", models.CharField(db_index=True, max_length=12)),
                ("sector", models.CharField(max_length=120)),
                ("rating", models.IntegerField()),
                ("preferred", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vendor catalog",
                "verbose_name_plural": "historical vendor catalogs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PartCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("part_number", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=255)),
                (
                    "mass_value",
                    models.DecimalField(
                        db_index=True, decimal_places=10, max_digits=30
                    ),
                ),
                ("mass_unit", models.CharField(max_length=30)),
                (
                    "mass",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="kg"
                    ),
                ),
                (
                    "volume_value",
                    models.DecimalField(
                        db_index=True, decimal_places=10, max_digits=30
                    ),
                ),
                ("volume_unit", models.CharField(max_length=30)),
                (
                    "volume",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="l"
                    ),
                ),
                (
                    "unit_cost_value",
                    models.DecimalField(
                        db_index=True, decimal_places=10, max_digits=30
                    ),
                ),
                ("unit_cost_unit", models.CharField(max_length=30)),
                (
                    "unit_cost",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="EUR"
                    ),
                ),
                ("reorder_threshold", models.IntegerField()),
                ("in_stock", models.BooleanField(default=False)),
                (
                    "hazard_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply.hazardclass",
                    ),
                ),
                (
                    "preferred_vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply.vendorcatalog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial", models.CharField(max_length=40, unique=True)),
                ("quantity", models.IntegerField()),
                ("received_on", models.DateField(blank=True, null=True)),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("reserved", models.BooleanField(default=False)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="maintenance.module",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply.partcatalog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalInventoryItem",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("serial", models.CharField(db_index=True, max_length=40)),
                ("quantity", models.IntegerField()),
                ("received_on", models.DateField(blank=True, null=True)),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("reserved", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="maintenance.module",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="supply.partcatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical inventory item",
                "verbose_name_plural": "historical inventory items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPartCatalog",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("part_number", models.CharField(db_index=True, max_length=30)),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=255)),
                (
                    "mass_value",
                    models.DecimalField(
                        db_index=True, decimal_places=10, max_digits=30
                    ),
                ),
                ("mass_unit", models.CharField(max_length=30)),
                (
                    "mass",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="kg"
                    ),
                ),
                (
                    "volume_value",
                    models.DecimalField(
                        db_index=True, decimal_places=10, max_digits=30
                    ),
                ),
                ("volume_unit", models.CharField(max_length=30)),
                (
                    "volume",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="l"
                    ),
                ),
                (
                    "unit_cost_value",
                    models.DecimalField(
                        db_index=True, decimal_places=10, max_digits=30
                    ),
                ),
                ("unit_cost_unit", models.CharField(max_length=30)),
                (
                    "unit_cost",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="EUR"
                    ),
                ),
                ("reorder_threshold", models.IntegerField()),
                ("in_stock", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "hazard_class",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="supply.hazardclass",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preferred_vendor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="supply.vendorcatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical part catalog",
                "verbose_name_plural": "historical part catalogs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCargoManifest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("tracking_code", models.CharField(db_index=True, max_length=40)),
                ("eta_date", models.DateField()),
                ("status", models.CharField(max_length=30)),
                ("priority", models.BooleanField(default=False)),
                (
                    "total_mass_value",
                    models.DecimalField(
                        db_index=True, decimal_places=10, max_digits=30
                    ),
                ),
                ("total_mass_unit", models.CharField(max_length=30)),
                (
                    "total_mass",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="kg"
                    ),
                ),
                (
                    "total_volume_value",
                    models.DecimalField(
                        db_index=True, decimal_places=10, max_digits=30
                    ),
                ),
                ("total_volume_unit", models.CharField(max_length=30)),
                (
                    "total_volume",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="l"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_module",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="maintenance.module",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="supply.vendorcatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cargo manifest",
                "verbose_name_plural": "historical cargo manifests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CargoManifest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_code", models.CharField(max_length=40, unique=True)),
                ("eta_date", models.DateField()),
                ("status", models.CharField(max_length=30)),
                ("priority", models.BooleanField(default=False)),
                (
                    "total_mass_value",
                    models.DecimalField(
                        db_index=True, decimal_places=10, max_digits=30
                    ),
                ),
                ("total_mass_unit", models.CharField(max_length=30)),
                (
                    "total_mass",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="kg"
                    ),
                ),
                (
                    "total_volume_value",
                    models.DecimalField(
                        db_index=True, decimal_places=10, max_digits=30
                    ),
                ),
                ("total_volume_unit", models.CharField(max_length=30)),
                (
                    "total_volume",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="l"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="maintenance.module",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supply.vendorcatalog",
                    ),
                ),
            ],
        ),
    ]
