# Generated by Django 5.2.10 on 2026-02-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalhazardclass",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical hazard class",
                "verbose_name_plural": "historical hazard classs",
            },
        ),
    ]
