name: ✨ Feature Request
description: Propose a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "discussion"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your idea! Tell us the problem and the ideal solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
      placeholder: Describe the user need or pain point.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should it work ideally?
      placeholder: Describe the API, CLI flags, settings, schema, etc.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives / Workarounds
      description: Any existing options or workarounds?
      placeholder: List alternatives if any.

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      options:
        - 🔥 Critical – blocks usage
        - ⚙️ Important – significant productivity gain
        - 💡 Nice-to-have – quality of life
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links, prior art, related issues/PRs, specs, or screenshots.
