"""Context manager utilities for tracking cache dependencies per thread."""

import threading
from types import TracebackType

from general_manager.cache.dependency_index import (
    Dependency,
    filter_type,
    general_manager_name,
)

_SUPPORTED_OPERATIONS: frozenset[filter_type] = frozenset(
    {"filter", "exclude", "identification", "request_query", "all"}
)


class _InvalidDependencyTrackerValueError(TypeError):
    """Internal error for malformed dependency tracker tuple values."""

    def __init__(self) -> None:
        """Build the malformed dependency tuple value error."""
        super().__init__("DependencyTracker values must be strings.")


class _InvalidDependencyTrackerOperationError(ValueError):
    """Internal error for unsupported dependency tracker operations."""

    def __init__(self, operation: object) -> None:
        """Build the unsupported operation error."""
        super().__init__(f"Unsupported dependency tracker operation: {operation!r}")


class _DependencyStorage(threading.local):
    """Thread-local dependency tracking stack."""

    def __init__(self) -> None:
        """Initialize an inactive dependency stack for one thread."""
        self.dependencies: list[set[Dependency]] = []
        self.depth = -1

    def reset(self) -> None:
        """Clear all active dependency scopes for the current thread."""
        self.dependencies.clear()
        self.depth = -1


_dependency_storage = _DependencyStorage()


class DependencyTracker:
    """Capture dependencies touched inside a read or cache-computation scope.

    Tracking is thread-local, not async task-local; same-thread async tasks share
    tracker state if their execution is interleaved inside one active context.
    """

    def __enter__(
        self,
    ) -> set[Dependency]:
        """Enter a dependency tracking context and return the current collector.

        Returns:
            Mutable set capturing dependencies discovered inside this context.
            A `Dependency` is `tuple[str, Literal["filter", "exclude",
            "identification", "request_query", "all"], str]`.
            Nested contexts receive their own set, and `track(...)` records each
            dependency in every active enclosing context. The returned set
            remains a usable snapshot after the context exits; clearing
            thread-local storage does not mutate sets that were already returned.
        """
        _dependency_storage.depth += 1
        _dependency_storage.dependencies.append(set())
        return _dependency_storage.dependencies[_dependency_storage.depth]

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None:
        """Leave the dependency tracking context and clean up this thread.

        Args:
            exc_type: Exception type raised within the context, if any.
            exc_val: Exception instance raised within the context, if any.
            exc_tb: Traceback generated by the exception, if any.

        The tracker does not suppress exceptions. Exiting the outermost context
        clears all thread-local tracking state; exiting a nested context removes
        only that nested collector. Calling `__exit__` after
        `reset_thread_local_storage()` or otherwise without an active context is
        a no-op.
        """
        if _dependency_storage.depth < 0:
            return
        if _dependency_storage.depth == 0:
            self.reset_thread_local_storage()
            return
        _dependency_storage.dependencies.pop()
        _dependency_storage.depth -= 1

    @staticmethod
    def track(
        class_name: general_manager_name,
        operation: filter_type,
        identifier: str,
    ) -> None:
        """Record a dependency tuple in all active tracking scopes.

        Args:
            class_name: Name of the GeneralManager subclass.
            operation: Operation being tracked, such as `filter`, `exclude`,
                `identification`, `request_query`, or `all`.
            identifier: String representation of the lookup parameters.

        Calling this method without an active `DependencyTracker` context is a
        no-op after validating the supplied values. Duplicate tuples collapse
        naturally because each collector is a set.

        Raises:
            TypeError: If `class_name`, `operation`, or `identifier` is not a
                string.
            ValueError: If `operation` is not one of `filter`, `exclude`,
                `identification`, `request_query`, or `all`.

        Concrete exception subclasses and messages are internal implementation
        details; callers should rely on the public base `TypeError` and
        `ValueError` contract.
        """
        if (
            not isinstance(class_name, str)
            or not isinstance(operation, str)
            or not isinstance(identifier, str)
        ):
            raise _InvalidDependencyTrackerValueError
        if operation not in _SUPPORTED_OPERATIONS:
            raise _InvalidDependencyTrackerOperationError(operation)
        DependencyTracker._track_validated(class_name, operation, identifier)

    @staticmethod
    def _track_validated(
        class_name: general_manager_name,
        operation: filter_type,
        identifier: str,
    ) -> None:
        """Record an already-validated dependency tuple in active collectors."""
        if _dependency_storage.depth < 0:
            return
        dependency = (class_name, operation, identifier)
        for dep_set in _dependency_storage.dependencies:
            dep_set.add(dependency)

    @staticmethod
    def is_active() -> bool:
        """Return whether dependency tracking is active for this execution context."""
        return _dependency_storage.depth >= 0

    @staticmethod
    def reset_thread_local_storage() -> None:
        """Clear all dependency tracking data for the current thread.

        It is safe to call with no active context or inside an active context.
        Already returned collector sets keep their current contents, later
        `track(...)` calls are ignored until a new context is entered, and the
        eventual `__exit__` for the reset context is a no-op.
        """
        _dependency_storage.reset()
