# Generated by Django 5.1.1 on 2024-11-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0003_historicalderivativevolume_derivativevolume"),
    ]

    operations = [
        migrations.AddField(
            model_name="derivative",
            name="price_unit",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="derivative",
            name="price_value",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=10, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalderivative",
            name="price_unit",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="historicalderivative",
            name="price_value",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=10, max_digits=30, null=True
            ),
        ),
    ]
