# Generated by Django 5.2.8 on 2025-12-15 18:41

import general_manager.measurement.measurement_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0007_alter_derivative_changed_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="derivative",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="derivativevolume",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="historicalderivative",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="historicalderivativevolume",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_active",
        ),
        migrations.AddField(
            model_name="derivative",
            name="estimated_weight",
            field=general_manager.measurement.measurement_field.MeasurementField(
                base_unit="kg", blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="derivative",
            name="price",
            field=general_manager.measurement.measurement_field.MeasurementField(
                base_unit="EUR", blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalderivative",
            name="estimated_weight",
            field=general_manager.measurement.measurement_field.MeasurementField(
                base_unit="kg", blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalderivative",
            name="price",
            field=general_manager.measurement.measurement_field.MeasurementField(
                base_unit="EUR", blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="total_capex",
            field=general_manager.measurement.measurement_field.MeasurementField(
                base_unit="EUR", blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_capex",
            field=general_manager.measurement.measurement_field.MeasurementField(
                base_unit="EUR", blank=True, null=True
            ),
        ),
    ]
