# Generated by Django 5.2.2 on 2025-06-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0005_historicalprojecttype_projecttype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprojecttype",
            name="changed_by",
        ),
        migrations.RemoveField(
            model_name="historicalprojecttype",
            name="history_user",
        ),
        migrations.RemoveConstraint(
            model_name="projecttype",
            name="unique_project_type",
        ),
        migrations.RemoveField(
            model_name="projecttype",
            name="changed_by",
        ),
        migrations.AlterField(
            model_name="projecttype",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name="HistoricalProjectType",
        ),
    ]
