# Generated by Django 5.2.10 on 2026-02-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = ()

    operations = (
        migrations.CreateModel(
            name="WorkflowEventRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=128, unique=True)),
                ("event_type", models.CharField(max_length=255)),
                ("event_name", models.CharField(blank=True, max_length=255, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(default=dict)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowExecutionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_id", models.CharField(max_length=128, unique=True)),
                ("workflow_id", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=32)),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(blank=True, null=True)),
                (
                    "correlation_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("dead_letter", "Dead Letter"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("available_at", models.DateTimeField(auto_now_add=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("claim_token", models.CharField(blank=True, max_length=64, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbox_entries",
                        to="general_manager.workfloweventrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("handler_registration_id", models.CharField(max_length=255)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("dead_letter", "Dead Letter"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("last_traceback", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="general_manager.workfloweventrecord",
                    ),
                ),
            ],
            options={"unique_together": {("event", "handler_registration_id")}},
        ),
        migrations.AddIndex(
            model_name="workfloweventrecord",
            index=models.Index(
                fields=["event_type"], name="general_man_event_t_55e4f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workfloweventrecord",
            index=models.Index(
                fields=["event_name"], name="general_man_event_n_33eb24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workfloweventrecord",
            index=models.Index(
                fields=["created_at"], name="general_man_created_5b1ca2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecutionrecord",
            index=models.Index(
                fields=["workflow_id", "state"], name="general_man_workflo_a2876f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecutionrecord",
            index=models.Index(
                fields=["correlation_id", "workflow_id"],
                name="general_man_correla_b2be1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecutionrecord",
            index=models.Index(
                fields=["created_at"], name="general_man_created_4dbaac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowoutbox",
            index=models.Index(
                fields=["status", "available_at"], name="general_man_status_180bed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowoutbox",
            index=models.Index(
                fields=["claim_token"], name="general_man_claim_t_78fd22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowoutbox",
            index=models.Index(
                fields=["created_at"], name="general_man_created_073f4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowdeliveryattempt",
            index=models.Index(
                fields=["status", "updated_at"], name="general_man_status_5f4aa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowdeliveryattempt",
            index=models.Index(
                fields=["handler_registration_id"],
                name="general_man_handler_f8368f_idx",
            ),
        ),
    )
