# Generated by Codex on 2026-06-20

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("general_manager", "0004_chat_persistence_models"),
        ("general_manager", "0004_search_index_state"),
    ]

    operations = []
