# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general_manager", "0005_merge_chat_search"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatpendingconfirmation",
            name="confirmation_id",
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name="chatpendingconfirmation",
            constraint=models.UniqueConstraint(
                condition=models.Q(resolved_at__isnull=True),
                fields=("conversation", "confirmation_id"),
                name="gm_chat_pending_conv_conf_uniq",
            ),
        ),
    ]
