# Generated by Django 5.2 on 2026-07-10

import uuid
from typing import Any

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_upload_quota_lock(apps: Any, schema_editor: Any) -> None:
    """Create the one durable upload-admission lock row."""
    lock_model = apps.get_model("general_manager", "UploadQuotaLock")
    lock_model.objects.using(schema_editor.connection.alias).get_or_create(pk=1)


def remove_upload_quota_lock(apps: Any, schema_editor: Any) -> None:
    """Remove the singleton row before reversing its model migration."""
    lock_model = apps.get_model("general_manager", "UploadQuotaLock")
    lock_model.objects.using(schema_editor.connection.alias).filter(pk=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("general_manager", "0006_chat_pending_confirmation_scoped_ids"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadQuotaLock",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("generation", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "constraints": (
                    models.CheckConstraint(  # type: ignore[call-arg]
                        condition=models.Q(("id", 1)),
                        name="gm_upload_quota_lock_singleton",
                    ),
                ),
            },
        ),
        migrations.RunPython(
            seed_upload_quota_lock,
            remove_upload_quota_lock,
        ),
        migrations.CreateModel(
            name="UploadIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_digest", models.CharField(max_length=64)),
                ("manager_name", models.CharField(max_length=255)),
                ("field_name", models.CharField(max_length=255)),
                (
                    "operation",
                    models.CharField(
                        choices=(("create", "Create"), ("update", "Update")),
                        max_length=16,
                    ),
                ),
                ("target_id", models.TextField(blank=True, null=True)),
                ("adapter_id", models.CharField(max_length=128)),
                ("adapter_version", models.CharField(max_length=64)),
                ("storage_fingerprint", models.CharField(max_length=255)),
                ("staging_key", models.CharField(max_length=1024)),
                ("transfer_attempt_count", models.PositiveIntegerField(default=0)),
                ("final_key", models.CharField(blank=True, max_length=1024, null=True)),
                ("old_key", models.CharField(blank=True, max_length=1024, null=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("declared_size", models.BigIntegerField()),
                ("declared_content_type", models.CharField(max_length=255)),
                ("declared_checksum_sha256", models.CharField(max_length=64)),
                ("verified_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "verified_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "verified_checksum_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("object_version", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=(
                            ("pending", "Pending"),
                            ("transferring", "Transferring"),
                            ("uploaded", "Uploaded"),
                            ("finalizing", "Finalizing"),
                            ("consumed", "Consumed"),
                            ("superseded", "Superseded"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ),
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "transfer_lease_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "finalization_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("finalization_attempt_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": (
                    models.Index(
                        fields=["state", "expires_at"],
                        name="gm_upload_state_exp_idx",
                    ),
                    models.Index(
                        fields=["user", "state"],
                        name="gm_upload_user_state_idx",
                    ),
                ),
                "constraints": (
                    models.CheckConstraint(  # type: ignore[call-arg]
                        condition=models.Q(("declared_size__gte", 0)),
                        name="gm_upload_declared_size_gte_0",
                    ),
                    models.CheckConstraint(  # type: ignore[call-arg]
                        condition=models.Q(
                            ("verified_size__isnull", True),
                            ("verified_size__gte", 0),
                            _connector="OR",
                        ),
                        name="gm_upload_verified_size_gte_0",
                    ),
                    models.CheckConstraint(  # type: ignore[call-arg]
                        condition=models.Q(("finalization_attempt_count__gte", 0)),
                        name="gm_upload_attempt_count_gte_0",
                    ),
                    models.CheckConstraint(  # type: ignore[call-arg]
                        condition=models.Q(("transfer_attempt_count__gte", 0)),
                        name="gm_upload_transfer_attempt_gte_0",
                    ),
                ),
            },
        ),
    ]
