# Generated by Django 5.2.10 on 2026-07-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general_manager", "0007_upload_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadintent",
            name="final_target_pk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadintent",
            name="final_object_version",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="uploadintent",
            name="old_cleanup_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadintent",
            name="old_cleanup_key",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="uploadintent",
            name="old_cleanup_version",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="uploadintent",
            name="old_object_version",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="uploadintent",
            name="verified_height",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadintent",
            name="verified_width",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
