# Generated by Django 5.2.10 on 2026-07-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general_manager", "0008_upload_finalization_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadintent",
            name="cleanup_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadintent",
            name="cleanup_error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="uploadintent",
            name="cleanup_lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadintent",
            name="cleanup_lease_token",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
