# Generated by Django 5.2.10 on 2026-07-17

from typing import Any

from django.db import migrations, models


def mark_unresolved_confirmations(apps: Any, schema_editor: Any) -> None:
    pending_confirmation = apps.get_model(
        "general_manager",
        "ChatPendingConfirmation",
    )
    pending_confirmation.objects.using(schema_editor.connection.alias).filter(
        resolved_at__isnull=True,
    ).update(unresolved_marker=True)


class Migration(migrations.Migration):
    dependencies = [
        ("general_manager", "0009_upload_cleanup_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatpendingconfirmation",
            name="unresolved_marker",
            field=models.BooleanField(default=None, editable=False, null=True),
        ),
        migrations.RunPython(
            mark_unresolved_confirmations,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="chatpendingconfirmation",
            name="unresolved_marker",
            field=models.BooleanField(default=True, editable=False, null=True),
        ),
        migrations.RemoveConstraint(
            model_name="chatpendingconfirmation",
            name="gm_chat_pending_conv_conf_uniq",
        ),
        migrations.AddConstraint(
            model_name="chatpendingconfirmation",
            constraint=models.UniqueConstraint(
                fields=("conversation", "confirmation_id", "unresolved_marker"),
                name="gm_chat_pending_conv_conf_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatpendingconfirmation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    resolved_at__isnull=True,
                    unresolved_marker=True,
                    unresolved_marker__isnull=False,
                )
                | models.Q(
                    resolved_at__isnull=False,
                    unresolved_marker__isnull=True,
                ),
                name="gm_chat_pending_resolution_state",
            ),
        ),
    ]
