# Generated by Django 5.2.16 on 2026-09-05 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general_manager", "0011_search_index_state_dirty_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="summarized_through",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="general_manager.chatmessage",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="tool_call_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="tool_calls",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
