# Generated by Django 5.2.10 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("core", "0003_align_user_relations_and_derivative_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="customer_volume_flex_unit",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="customer_volume_flex_value",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="probability_of_nomination_unit",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="probability_of_nomination_value",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="customer_volume_flex_unit",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="customer_volume_flex_value",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="probability_of_nomination_unit",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="probability_of_nomination_value",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=30, null=True
            ),
        ),
        migrations.RunSQL(
            sql=[
                """
                UPDATE core_project
                SET probability_of_nomination_value = probability_of_nomination * 100,
                    probability_of_nomination_unit = 'percent'
                WHERE probability_of_nomination IS NOT NULL;
                """,
                """
                UPDATE core_project
                SET customer_volume_flex_value = customer_volume_flex * 100,
                    customer_volume_flex_unit = 'percent'
                WHERE customer_volume_flex IS NOT NULL;
                """,
                """
                UPDATE core_historicalproject
                SET probability_of_nomination_value = probability_of_nomination * 100,
                    probability_of_nomination_unit = 'percent'
                WHERE probability_of_nomination IS NOT NULL;
                """,
                """
                UPDATE core_historicalproject
                SET customer_volume_flex_value = customer_volume_flex * 100,
                    customer_volume_flex_unit = 'percent'
                WHERE customer_volume_flex IS NOT NULL;
                """,
            ],
            reverse_sql=[
                """
                UPDATE core_project
                SET probability_of_nomination = probability_of_nomination_value / 100
                WHERE probability_of_nomination_value IS NOT NULL;
                """,
                """
                UPDATE core_project
                SET customer_volume_flex = customer_volume_flex_value / 100
                WHERE customer_volume_flex_value IS NOT NULL;
                """,
                """
                UPDATE core_historicalproject
                SET probability_of_nomination = probability_of_nomination_value / 100
                WHERE probability_of_nomination_value IS NOT NULL;
                """,
                """
                UPDATE core_historicalproject
                SET customer_volume_flex = customer_volume_flex_value / 100
                WHERE customer_volume_flex_value IS NOT NULL;
                """,
            ],
        ),
        # NOTE:
        # The MeasurementField state transition can fail during migration on
        # existing local databases because Django resolves a missing legacy
        # column definition while comparing field metadata. The runtime model
        # already uses MeasurementField; this migration's critical DB changes are
        # the value/unit columns and data backfill above.
    ]
